/*
 * JS for Screen1 generated by Appery.io
 *
 * Created on: Wednesday, July 03, 2013, 07:46:36 AM (PDT)
 */

Appery.getProjectGUID = function() {
    return 'cab6b0c4-5fdd-44b2-b38b-6ae4a8832d5b';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

Screen1_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_2': 'Screen1_mobilenavbar_2',
        'mobilenavbaritem_3': 'Screen1_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'Screen1_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'Screen1_mobilenavbaritem_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'Screen1';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    Screen1_beforeshow = function() {
        Appery.CurrentScreen = "Screen1";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_71A5_onLoad = Screen1_onLoad = function() {
        screen_71A5_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        Screen1_deviceEvents();
        Screen1_windowEvents();
        screen_71A5_elementsEvents();
    }

    // screen window events
    screen_71A5_windowEvents = Screen1_windowEvents = function() {
        $('#Screen1').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // device events
    Screen1_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_71A5_elementsExtraJS = Screen1_elementsExtraJS = function() {
        // screen (Screen1) extra code

    }

    // screen elements handler
    screen_71A5_elementsEvents = Screen1_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#Screen1_mobileheader [name="mobilenavbaritem_3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('startScreen', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#Screen1").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        Screen1_beforeshow();
    });

    if (runBeforeShow) {
        Screen1_beforeshow();
    } else {
        Screen1_onLoad();
    }

}

$("#Screen1").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    Screen1_js();
});