/*
 * JS for startScreen generated by Appery.io
 *
 * Created on: Wednesday, July 03, 2013, 07:46:36 AM (PDT)
 */

Appery.getProjectGUID = function() {
    return 'cab6b0c4-5fdd-44b2-b38b-6ae4a8832d5b';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

startScreen_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'startScreen_mobilelabel_2',
        'zipCodeInput': 'startScreen_zipCodeInput',
        'mobilebutton_4': 'startScreen_mobilebutton_4',
        'temperature': 'startScreen_temperature',
        'icon': 'startScreen_icon',
        'mobilebutton_5': 'startScreen_mobilebutton_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    weather = new Appery.DataSource(getWeather, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("startScreen");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['data', 'weather[0]', 'tempMaxF'],
            'ID': 'temperature',
            'ATTR': '@'
        }, {
            'PATH': ['data', 'weather[0]', 'weatherIconUrl[0]', 'value'],
            'ID': 'icon',
            'ATTR': 'src'
        }],
        'requestMapping': [{
            'PATH': ['q'],
            'ID': 'zipCodeInput',
            'ATTR': 'value'
        }, {
            'PATH': ['format'],
            'ATTR': 'json'
        }, {
            'PATH': ['key'],
            'ATTR': 'p2kwtzs9j97azvg4zf2n4a8b'
        }]
    });

    datasources.push(weather);

    /*
     * Events and handlers
     */

    // Before Show
    startScreen_beforeshow = function() {
        Appery.CurrentScreen = "startScreen";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_3671_onLoad = startScreen_onLoad = function() {
        screen_3671_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        startScreen_deviceEvents();
        startScreen_windowEvents();
        screen_3671_elementsEvents();
    }

    // screen window events
    screen_3671_windowEvents = startScreen_windowEvents = function() {
        $('#startScreen').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // device events
    startScreen_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_3671_elementsExtraJS = startScreen_elementsExtraJS = function() {
        // screen (startScreen) extra code

    }

    // screen elements handler
    screen_3671_elementsEvents = startScreen_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#startScreen_mobilecontainer1 [name="mobilebutton_4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        weather.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };

                }
            },
        });

        $('#startScreen_mobilecontainer1 [name="mobilebutton_5"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('Screen1', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#startScreen").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }

}

$("#startScreen").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    startScreen_js();
});